### ISSUE TITLE
Perfect theme -- two ideas

### ISSUE THREAD

**Issue by EdmundsEcho** [eendroroy/nothing#1]
As simple as your theme is, it is exactly what I needed.  Thank you!  Suggestions:

1. implement the theme with either documentation or a function that enables quick toggling between command promps (e.g., between nothing and robbyrussell).  Right now the use of the autoloading hook function requires I quit terminal (or iTerm) to use another prompt.

2. have a setting to disable the pseudo line number count.  Go pure nothing!

Again, just ideas.

**Comment by eendroroy** [comment]
Thanks for the great ideas @EdmundsEcho .
I am not sure about no. 1, IMHO it seems like the quicker prompt switching is something better to be done  in a separate plug-in of some kind.

Absolutely love the idea of disabling the line number count. :+1:

**Comment by EdmundsEcho** [comment]
Great!  I agree that another plugin makes sense for the swapping idea.  Here is something I did over the weekend.  It might be a useful repository.

```
#!/usr/bin/env zsh

# change-zsh-theme.sh new_theme
#---------------------------------------------------------------
# TODO: verify that the new theme exists
#       use autoload -U add-zsh-hook to force cursor update
#
# Note: If a theme is replaced with one that does not exist
#       oh-my-xsh defaults to `robbyrussell`.  The requested
#       theme must already have an entry in the config
#       file.  This script only toggles commenting in/out
#       to activate a theme entry. Finally, the zshrc file
#       is copied to a backup before changes are maded file
#       if required (e.g., zshrc_bk).
#
#---------------------------------------------------------------
ZSHRC=$HOME/dotfiles/zshrc
#---------------------------------------------------------------

PROGNAME=${0##*/}
ARGS=1

main () {
  validate_input $#
  swap_themes $@
  echo "Updated zshr. Source the file to see changes."
  exit 0
}

swap_themes () {

  NEW_THEME=$1
  TEMP_FILE=/tmp/swap_themes.$$.$RANDOM

  # backup .zshrc
  cp $ZSHRC ${ZSHRC}_bk

  # Comment out the line with an active theme
  sed -E "s/^(ZSH_THEME=.+\")/# \1/" $ZSHRC > $TEMP_FILE

  # Activate the chosen theme
  sed -E "s/^# +(ZSH_THEME=\"$NEW_THEME\".*)/\1/" $TEMP_FILE > $ZSHRC

  rm -f $TEMP_FILE
}

err () {
  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@" >&2
}

validate_input () {
  if [[ $1 -lt $ARGS ]]; then
    err "Usage: $PROGNAME new-theme-name"
    exit 128
  fi
}

main "$@"
exit 0
```

**Comment by eendroroy** [comment]
You can start writing a plugin with it. Also sourcing the .zshrc file automatically after changing the theme would be great.

Support for popular plugin managers like `antigen`, `zplug`, `zgen` can be added.

**Comment by EdmundsEcho** [comment]
I tried to include sourcing the file once changed.  However, I ran into errors that I could not seem to figure out.  I even went so far as to create a function in my .zshrc file to include a reload there.   However, I could not get the error handling right...  Any ideas?

```
# ---------------------------------------------------------
# User defined functions
# ---------------------------------------------------------
swapzt() {
  swap-zsh-themes.sh $@;
  source ~/.zshrc;
}
```

**Comment by eendroroy** [comment]
**Just an idea**. There may be some function that gets defined by sourcing the `.zshrc` file. While trying to sourcing the `.zshrc` file the second time, it tries to redefine the function already defined.

**Comment by eendroroy** [comment]
BTW, could you please include the full error message here?

**Comment by EdmundsEcho** [comment]
It works as I have described it in the function.  I was mistaken.  It is when I try to force source in the `swap-zsh-themes.sh` that it either does not reset the prompt, or crashes depending on how I execute the command...
